# fly.toml file generated for stripe-sync on 2022-08-06T16:53:05-04:00

app = "stripe-sync"

[env]
  AUTH0_CLIENT_ID = "UwuDuHkLYALBkqCvQneHo9UDyrJ1WN7j"
  AUTH0_DOMAIN = "supabase-dev.auth0.com"
  LOG_LEVEL = "debug"
  NODE_ENV = "production"
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
    [services.ports.tls_options]
      default_self_signed = true

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
